#!/bin/bash
set -euo pipefail

# Links global agent instructions into each agent's config.
#
# Usage:
#   ./create-agent-instructions-symlinks.sh                  # link MY_AGENTS.md directly
#   ./create-agent-instructions-symlinks.sh --overlay PATH   # link MY_AGENTS.md + PATH
#
# Codex and Pi cannot include other files, so an overlay is concatenated onto
# MY_AGENTS.md in a generated, gitignored build/AGENTS.md. Re-run the script
# after editing either file. Keep confidential overlays outside this public repo.

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
CORE="${SCRIPT_DIR}/MY_AGENTS.md"
GENERATED="${SCRIPT_DIR}/build/AGENTS.md"
OVERLAY=""

while [[ $# -gt 0 ]]; do
	case "$1" in
	--overlay)
		if [[ $# -lt 2 ]]; then
			echo "--overlay requires a path" >&2
			exit 1
		fi
		OVERLAY="$2"
		shift 2
		;;
	*)
		echo "Unknown argument: $1" >&2
		exit 1
		;;
	esac
done

for file in "$CORE" ${OVERLAY:+"$OVERLAY"}; do
	if [[ ! -f "$file" ]]; then
		echo "Source file not found: $file" >&2
		exit 1
	fi
done

if [[ -n "$OVERLAY" ]]; then
	mkdir -p "$(dirname -- "$GENERATED")"
	{
		printf '<!-- Generated by %s; edit MY_AGENTS.md or %s instead. -->\n\n' \
			"$(basename -- "${BASH_SOURCE[0]}")" "$OVERLAY"
		cat "$CORE"
		printf '\n'
		cat "$OVERLAY"
	} >"${GENERATED}.tmp"
	mv "${GENERATED}.tmp" "$GENERATED"
	echo "Generated: $GENERATED"
	SOURCE="$GENERATED"
else
	SOURCE="$CORE"
fi

TARGETS=(
	"${HOME}/.codex/AGENTS.md"
	"${HOME}/.claude/CLAUDE.md"
	"${HOME}/.pi/agent/AGENTS.md"
)

for target in "${TARGETS[@]}"; do
	mkdir -p "$(dirname -- "$target")"

	if [[ -e "$target" || -L "$target" ]]; then
		current="$(readlink "$target" 2>/dev/null || true)"
		if [[ "$current" == "$SOURCE" ]]; then
			echo "Already linked: $target"
			continue
		fi
		# Switching between the direct and overlay modes replaces our own links.
		if [[ "$current" != "$CORE" && "$current" != "$GENERATED" ]]; then
			echo "Refusing to replace existing path: $target" >&2
			exit 1
		fi
		rm "$target"
	fi

	ln -s "$SOURCE" "$target"
	echo "Linked: $target -> $SOURCE"
done
